### ISSUE TITLE
Создание объекта для поста

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/fsn#4]
Создать класс, который инкапулирует данные о посте, в частности аккаунт пользователя, дату поста, ссылку на него и его текст

**Comment by GreStas** [comment]
Не знаю как взять на себя эту задачу, поэтому просто сообщаю, что начинаю разработку этого класса.
Исхожу из того, что на базе этого класса в дальнейшем можно будет сделать отдельные классы-наследники для каждого источника (Twtr, FB, etc)

**Comment by GreStas** [comment]
Модуль posts
class Post
global variable datetime_format
